name: Create External Folder Releases and Manifest

on:
  release:
    types: [published]

jobs:
  create_zips_and_manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub requests pyyaml GitPython

      - name: Get changed table.yml files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -w 'table\.yml$')
          echo "CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ',')" >> $GITHUB_OUTPUT
  
      - name: Validate table.yml files
        run: |
          if [[ -n "${{ steps.changed-files.outputs.CHANGED_FILES }}" ]]; then
            IFS=',' read -ra FILES <<< "${{ steps.changed-files.outputs.CHANGED_FILES }}"
            for file in "${FILES[@]}"; do
              echo "Checking \"$file\""
              python .github/workflows/scripts/validate-table-yaml.py "$file"
              yamllint -c .yamllint "$file"
            done
          else
            echo "No table.yml files were changed."
          fi

      - name: Generate release files
        run: python .github/workflows/scripts/generate-release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.event.release.tag_name }}

      - name: Update Release notes
        run: python .github/workflows/scripts/generate-release-notes.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.event.release.tag_name }}
